### ISSUE TITLE
Percentage text appear outside the circle

### ISSUE THREAD

**Issue by avivbiton** [mesthabro/react-gradient-progress#2]
![bug](https://user-images.githubusercontent.com/39068976/63930546-38304400-ca5c-11e9-8f7b-012acdb3553b.PNG)

This happens in my React project.  
Not sure if there is any CSS property in my project that causes this, but I've tried disabling CSS properties the may affect the Component but the issue still happen.

**Comment by prasannamestha** [comment]
This is most probably caused due to css name conflicts. If possible could you provide a sample code to reproduce this issue?

**Comment by avivbiton** [comment]
Nevermind, it was a problem on my end, it works as intended now.
